// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4MS35NShhVCUTYFau86BAvZZvbcBW0vA',
    appId: '1:59237454061:web:2d428f112354280cf0fce4',
    messagingSenderId: '59237454061',
    projectId: 'mini-project-4850a',
    authDomain: 'mini-project-4850a.firebaseapp.com',
    storageBucket: 'mini-project-4850a.appspot.com',
    measurementId: 'G-P02JXDT33P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4MS35NShhVCUTYFau86BAvZZvbcBW0vA',
    appId: '1:59237454061:android:304ceeda364b8f16f0fce4',
    messagingSenderId: '59237454061',
    projectId: 'mini-project-4850a',
    storageBucket: 'mini-project-4850a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4MS35NShhVCUTYFau86BAvZZvbcBW0vA',
    appId: '1:59237454061:ios:9e478a2d01bfbb25f0fce4',
    messagingSenderId: '59237454061',
    projectId: 'mini-project-4850a',
    storageBucket: 'mini-project-4850a.appspot.com',
    iosBundleId: 'com.example.miniProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4MS35NShhVCUTYFau86BAvZZvbcBW0vA',
    appId: '1:59237454061:ios:9e478a2d01bfbb25f0fce4',
    messagingSenderId: '59237454061',
    projectId: 'mini-project-4850a',
    storageBucket: 'mini-project-4850a.appspot.com',
    iosBundleId: 'com.example.miniProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4MS35NShhVCUTYFau86BAvZZvbcBW0vA',
    appId: '1:59237454061:web:414b48875301be5cf0fce4',
    messagingSenderId: '59237454061',
    projectId: 'mini-project-4850a',
    authDomain: 'mini-project-4850a.firebaseapp.com',
    storageBucket: 'mini-project-4850a.appspot.com',
    measurementId: 'G-TPWESLR1MZ',
  );
}
